from ...Fields import UInt8Field, Int16Field
from . import Model, Int32Field, FloatField


class EntityData(Model):
    version = UInt8Field()
    id = Int32Field()
    protoId = Int16Field()
    modelIndex = Int16Field()
    pos_x = FloatField()
    pos_y = FloatField()
    pos_z = FloatField()
    rot_x = FloatField()
    rot_y = FloatField()
    rot_z = FloatField()
    rot_w = FloatField()
    beltId = Int32Field()
    splitterId = Int32Field()
    storageId = Int32Field()
    tankId = Int32Field()
    minerId = Int32Field()
    inserterId = Int32Field()
    assemblerId = Int32Field()
    fractionateId = Int32Field()
    ejectorId = Int32Field()
    siloId = Int32Field()
    labId = Int32Field()
    stationId = Int32Field()
    powerNodeId = Int32Field()
    powerGenId = Int32Field()
    powerConId = Int32Field()
    powerAccId = Int32Field()
    powerExcId = Int32Field()
    monsterId = Int32Field()
