from ...Fields import FloatField, BoolField
from . import Model, Int32Field


class EjectorComponent(Model):
    version = Int32Field()
    id = Int32Field()
    entityId = Int32Field()
    planetId = Int32Field()
    pcId = Int32Field()
    direction = Int32Field()
    time = Int32Field()
    fired = BoolField()
    chargeSpend = Int32Field()
    coldSpend = Int32Field()
    bulletId = Int32Field()
    bulletCount = Int32Field()
    orbitId = Int32Field()
    pivotY = FloatField()
    muzzleY = FloatField()
    localPosN_x = FloatField()
    localPosN_y = FloatField()
    localPosN_z = FloatField()
    localAlt = FloatField()
    localRot_x = FloatField()
    localRot_y = FloatField()
    localRot_z = FloatField()
    localRot_w = FloatField()
    localDir_x = FloatField()
    localDir_y = FloatField()
    localDir_z = FloatField()
