from ...Fields import Int16Field, Int64Field, FloatField, BoolField
from . import Model, Int32Field


class PowerGeneratorComponent(Model):
    version = Int32Field()
    id = Int32Field()
    entityId = Int32Field()
    networkId = Int32Field()
    photovoltaic = BoolField()
    wind = BoolField()
    gamma = BoolField()
    genEnergyPerTick = Int64Field()
    useFuelPerTick = Int64Field()
    fuelMask = Int16Field()
    fuelEnergy = Int64Field()
    curFuelId = Int16Field()
    fuelId = Int16Field()
    fuelCount = Int16Field()
    fuelHeat = Int64Field()
    catalystId = Int32Field()
    catalystPoint = Int32Field()
    productId = Int32Field()
    productCount = FloatField()
    productHeat = Int64Field()
    warmup = FloatField()
    ionEnhance = FloatField()
    x = FloatField()
    y = FloatField()
    z = FloatField()
